version: "3.8"
services:
  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

  friend-service:
    build: .
    image: friend-service
    depends_on:
      - mongodb
    ports:
      - "80:3000"
    env_file:
      - .env

volumes:
  dbdata6:
